/* THIS FILE IS GENERATED BY THESNOWFIELD MANUALLY. */
/* PLEASE DO NOT DELETE OR EDIT THIS FILE! */

#ifndef _FROST_CALLBACK_H
#define _FROST_CALLBACK_H

#define call_task_callback(task) task->callback()

#define call_task_callback_arg1(task) \
  ((frost_callback_arg1_t)task->callback)((frost_handle_t)(frost_handle_t)task->args.argv[0])

#define call_task_callback_arg2(task) \
  ((frost_callback_arg2_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1])

#define call_task_callback_arg3(task) \
  ((frost_callback_arg3_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2])

#define call_task_callback_arg4(task) \
  ((frost_callback_arg4_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3])

#define call_task_callback_arg5(task) \
  ((frost_callback_arg5_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4])

#define call_task_callback_arg6(task) \
  ((frost_callback_arg6_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5])

#define call_task_callback_arg7(task) \
  ((frost_callback_arg7_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6])

#define call_task_callback_arg8(task) \
  ((frost_callback_arg8_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6],(frost_handle_t)task->args.argv[7])

#define call_task_callback_arg9(task) \
  ((frost_callback_arg9_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6],(frost_handle_t)task->args.argv[7],(frost_handle_t)task->args.argv[8])

#define call_task_callback_arg10(task) \
  ((frost_callback_arg10_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6],(frost_handle_t)task->args.argv[7],(frost_handle_t)task->args.argv[8],(frost_handle_t)task->args.argv[9])

#define call_task_callback_arg11(task) \
  ((frost_callback_arg11_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6],(frost_handle_t)task->args.argv[7],(frost_handle_t)task->args.argv[8],(frost_handle_t)task->args.argv[9],(frost_handle_t)task->args.argv[10])

#define call_task_callback_arg12(task) \
  ((frost_callback_arg12_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6],(frost_handle_t)task->args.argv[7],(frost_handle_t)task->args.argv[8],(frost_handle_t)task->args.argv[9],(frost_handle_t)task->args.argv[10],(frost_handle_t)task->args.argv[11])

#define call_task_callback_arg13(task) \
  ((frost_callback_arg13_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6],(frost_handle_t)task->args.argv[7],(frost_handle_t)task->args.argv[8],(frost_handle_t)task->args.argv[9],(frost_handle_t)task->args.argv[10],(frost_handle_t)task->args.argv[11],(frost_handle_t)task->args.argv[12])

#define call_task_callback_arg14(task) \
  ((frost_callback_arg14_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6],(frost_handle_t)task->args.argv[7],(frost_handle_t)task->args.argv[8],(frost_handle_t)task->args.argv[9],(frost_handle_t)task->args.argv[10],(frost_handle_t)task->args.argv[11],(frost_handle_t)task->args.argv[12],(frost_handle_t)task->args.argv[13])

#define call_task_callback_arg15(task) \
  ((frost_callback_arg15_t)task->callback)((frost_handle_t)task->args.argv[0],(frost_handle_t)task->args.argv[1],(frost_handle_t)task->args.argv[2],(frost_handle_t)task->args.argv[3],(frost_handle_t)task->args.argv[4],(frost_handle_t)task->args.argv[5],(frost_handle_t)task->args.argv[6],(frost_handle_t)task->args.argv[7],(frost_handle_t)task->args.argv[8],(frost_handle_t)task->args.argv[9],(frost_handle_t)task->args.argv[10],(frost_handle_t)task->args.argv[11],(frost_handle_t)task->args.argv[12],(frost_handle_t)task->args.argv[13],(frost_handle_t)task->args.argv[14])

static void __invoke_task_callback(frost_task_ctx_t* ctx) {
  switch(ctx->args.argc) {
    case 0: call_task_callback(ctx); break;
    case 1: call_task_callback_arg1(ctx); break;
    case 2: call_task_callback_arg2(ctx); break;
    case 3: call_task_callback_arg3(ctx); break;
    case 4: call_task_callback_arg4(ctx); break;
    case 5: call_task_callback_arg5(ctx); break;
    case 6: call_task_callback_arg6(ctx); break;
    case 7: call_task_callback_arg7(ctx); break;
    case 8: call_task_callback_arg8(ctx); break;
    case 9: call_task_callback_arg9(ctx); break;
    case 10: call_task_callback_arg10(ctx); break;
    case 11: call_task_callback_arg11(ctx); break;
    case 12: call_task_callback_arg12(ctx); break;
    case 13: call_task_callback_arg13(ctx); break;
    case 14: call_task_callback_arg14(ctx); break;
    case 15: call_task_callback_arg15(ctx); break;
  }
}

#endif /* _FROST_CALLBACK_H */
